### ISSUE TITLE
Add standard gems

### ISSUE THREAD

**Issue by hortongn** [uclibs/adopt-a-book#2]
Depends on #1

Use a separate commit for each of the following:

- [x] Use ruby 2.6.5 (.ruby-version) 
- [x] Install and configure Rspec
- [x] Install and configure Rubocop
- [x] Install and configure Coveralls
- [x] Install and configure Dotenv
- [x] Install and configure Circle-CI
- [x] Install byebug

**Comment by priyakvs** [comment]
I think we can close this since byebug is already installed. @hortongn
